# server info
all: 
  git_repository: git@github.com:CedricWagner/SiteRecettes.git
  project_code: SiteRecettes
  # set to false to not fire those tasks
  use_composer: true
  use_npm: true
  # the npm deployment method. "local"|"remote" (default:"remote")
  # "local" will send your local files to the remote
  # "remote" will run "npm run prod" on the remote
  npm_mode: remote
  # the directory of the application, relative to root_path
  app_path: /
  # the public directory, relative to root_path
  public_path: web
  # the directory where package.json is set, relative to root_path
  npm_path: react_app/
  # (only if npm_mode="local") 
  # the list of folders that will be sent to remote 
  # npm_dist_path: 
  #   - relative/path/to/dist

stage:
  host: 51.254.102.71
  port: 22
  user: debian
  # Optionnal use this only if php is not ok
  # php_path: /usr/local/php7.2/bin/php
  # the root dir of the project
  root_path: /var/www/subdomains/les-veganeries-de-dodo
  # path of the composer.phar that should be used
  composer_path: /usr/bin/composer
  branch: staging