<?php

/**
 * @file
 * Contains custom_serializers.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function custom_serializers_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the custom_serializers module.
    case 'help.page.custom_serializers':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Add new serializers for contents') . '</p>';
      return $output;

    default:
  }
}
