<?php

/**
 * @file
 * Contains admin_tweaks.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function admin_tweaks_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the admin_tweaks module.
    case 'help.page.admin_tweaks':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Changes some aspects of the admin UI and behaviors') . '</p>';
      return $output;

    default:
  }
}

function admin_tweaks_preprocess_page(&$variables) {
  if (\Drupal::service('router.admin_context')->isAdminRoute()) {
    $variables['#attached']['library'][] = 'admin_tweaks/admin_tweaks';
   }
}